dataset:
  data_dir: /mnt/truenas/scratch/kuangye.chen/dataset/
  train_data_lst: train.txt

mobilenet_v2:
  net_config:
    - [1, 16, 1, 1]
    - [6, 24, 2, 2]
    - [6, 32, 3, 2]
    - [6, 64, 4, 2]
    - [6, 96, 3, 1]
    - [6, 160, 3, 2]
    - [6, 320, 1, 1]
  num_output: 60

train:
  batch_size: 20
  shuffle: True
  optimizer:
    name: adam
    learning_rate: 0.01
    momentum: 0.8
    wd: 0.0005
  lr_scheduler:
    factor: 0.9
    step: 600
  log_frequent: 20
  begin_epoch: 0
  end_epoch: 200

misc:
  checkpoint_dir: ./model
  checkpoint_prefix: mobilenet
  checkpoint_period: 1
  num_checkpoint: 20